### ISSUE TITLE
Date of Birth with spaces not being recognized

### ISSUE THREAD

**Issue by mscarey** [scrapd/scrapd#128]
Issue Type
----------

- Bug report

Current Behavior
----------------

The parser fails to recognize a date of birth in the "Deceased" field if it's in a format like: 

> Deceased:  John Doe, Black male, D.O.B. January 1, 2000

Instead, the parser assigns a date of birth in 2019.

Expected Behavior
-----------------

The parser should recognize the date and store it (as a datetime.date, in my opinion).

Possible Solution
-----------------

Currently the date parsing is based on assumption that when you split the Deceased field on spaces, the DOB will be one item in the resulting list. That aspect will have to change, because this date format contains spaces.

Steps to Reproduce
------------------

1. Try to parse http://austintexas.gov/news/traffic-fatality-29-3

Context
-------

One of the entries on https://viz.scrapd.org/ has an age of -1.

**Comment by rgreinho** [comment]
This should be fixed once #132 gets merged.

**Comment by anthonybaulo** [comment]
https://github.com/scrapd/scrapd/pull/132 creates a dedicated function to parse the date field. I don't think it will affect the parsing of the deceased field. 

However, `search_dates()` from `dateparser.search`, which I used in `parse_date_field()` shown below, will handle the problematic example listed in this issue. Removing any periods (`.replace('.', ' ')`) before using `search_dates()` is necessary for consistent results.
```python
from dateparser.search import search_dates
...
def parse_date_field(page):
    """
    Extract the date from the content of the fatality page.

    :param str page: the content of the fatality page
    :return: a string representing the date.
    :rtype: str
    """
    date_pattern = re.compile(
        r'''
        >Date:          # The name of the desired field.
        .*\s{2,}        # Any character and whitespace.
        (?:</strong>)?  # Non-capture (literal match).
        ([^<]*)         # Capture any character except '<'.
        <               # Non-capture (literal match)
        ''',
        re.VERBOSE,
    )
    date = match_pattern(page, date_pattern).replace('.', ' ')
    date = search_dates(date)
    return date[0][1].strftime("%m/%d/%Y") if date else ''
```

**Comment by rgreinho** [comment]
You're correct, I was too quick on commenting the issue. But yes, I am still confident that this issue can easily be solved with `search_dates()`.

However, I am kind of surprised to see a dot (`.`) in the  as a parsing issue. I tried it in `dateparser` and it worked fine:

```python
>>> import dateparser
>>> dateparser.parse('Wednesday, Oct. 3, 2018')
datetime.datetime(2018, 10, 3, 0, 0)
>>>
```

**Comment by rgreinho** [comment]
And yes, with `date parser` to the rescue:

```python
>>> from dateparser.search import search_dates
>>> search_dates('Deceased: John Doe, Black male, D.O.B. January 1, 2000')
[('January 1, 2000', datetime.datetime(2000, 1, 1, 0, 0))]
```

**Comment by anthonybaulo** [comment]
When the period is part of the date (e.g. Jan.) there is a problem:

```python
>>> from dateparser.search import search_dates
>>> search_dates('Deceased: John Doe, Black male, D.O.B. Jan. 1, 2000')
[('Jan', datetime.datetime(2019, 1, 24, 0, 0)), ('1, 2000', datetime.datetime(2000, 1, 24, 0, 0))]
```

**Comment by rgreinho** [comment]
claimed by @matt.
