### ISSUE TITLE
Incorrect age/DOB parsing

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapd#150]
Issue Type
----------

- Bug report
- Feature request

Current Behavior
----------------

The following entries have the age/DOB parsed incorrectly:

* https://austintexas.gov/news/traffic-fatality-20-4
* https://austintexas.gov/news/traffic-fatality-29-3

**Comment by mscarey** [comment]
I just made a PR for https://austintexas.gov/news/traffic-fatality-29-3 at #155.
I added a passing test for handling https://austintexas.gov/news/traffic-fatality-20-4 with the `process_deceased_field` function in #125. So the issue must be somewhere in the pipeline outside that function.

**Comment by rgreinho** [comment]
Thanks for the PR @mscarey I'll review it shortly.

Regarding, the other fatality (20-4), I checked and the problem is not in the pipeline. You can reproduce it with the following command:

```bash
$ scrapd --version
scrapd, version 2.0.0

$ scrapd -v --format json --from "April 18, 2019" --to "April 18, 2019"
[
  {
    "Age": -1,
    "Case": "19-1080319",
    "DOB": "06/19/2019",
    "Date": "04/18/2019",
    "Ethnicity": "Hispanic",
    "Fatal crashes this year": "20",
    "Gender": "male",
    "Link": "http://austintexas.gov/news/traffic-fatality-20-4",
    "Location": "8000 block of West U.S. 290",
    "Notes": "This is Austin\u2019s 20th fatal traffic crash of 2019, resulting in 21 fatalities this year. At this time in 2018, there were 19 fatal traffic crashes and 20 traffic fatalities.",
    "Time": "06:53 a.m."
  },
  ...
]
```
