### ISSUE TITLE
Stop parsing Notes from Twitter description

### ISSUE THREAD

**Issue by mscarey** [scrapd/scrapd#187]
Issue Type
----------

- Code cleanup

Current Behavior
----------------

Each bulletin has not just text for display on the webpage, but also a `twitter_description` field that duplicates some of the text from the page. Sometimes this field contains the `Notes` field that describes the collision, but sometimes it doesn't. Currently the parser attempts to parse the `Notes` field from the `twitter_description` field, and then only if that first attempt failed, it tries again to get the Notes from the text displayed on the page.

This creates burdensome complexity and it creates confusion about what the parser will output. 

Expected Behavior
-----------------

The parser could make only one attempt to parse Notes.

Possible Solution
-----------------

We could change the parser to no longer parse Notes from the `twitter_description`, if we can also verify that this change doesn't introduce new parsing errors.

Context
-------

@rgreinho [said more](https://github.com/scrapd/scrapd/pull/184#discussion_r318313684) about the rationale for this change in comments to PR #184.

**Comment by rgreinho** [comment]
Completed in #199.
