### ISSUE TITLE
Add Full Name field

### ISSUE THREAD

**Issue by mscarey** [scrapd/scrapd#193]
Issue Type
----------

- Feature request

Current Behavior
----------------

The viz provides a first and last name for each deceased person.

Expected Behavior
-----------------

The viz provides the deceased person's name in exactly the same form as it appeared in the police bulletin.

Possible Solution
-----------------

I suggest just adding a Full Name field to the records returned by the scraper. Don't stop collecting the First Name and Last Name fields because they could be useful. Display the Full Name field in the viz, and stop displaying the First and Last fields.

This will change both the data row format and the layout of the viz page, but they don't seem like drastic changes.

Steps to Reproduce
------------------

1. visit <https://viz.scrapd.org/>

Context
-------

I don't remember the details, but @rgreinho said that a user preferred to have names presented as full names.

**Comment by rgreinho** [comment]
Here is the original message we received from a user:

> Out of respect to victims and families, I'd like to read victims' names exactly as recorded on the APD press releases. But the First Name and Last Name column format on the ScrAPD page strips out most of that data. What do you think about having just a Name column that records as many names as that person has?

I would like to avoid having data duplication within the data set entries. Therefore I would propose the following approaches:
* Add a middle name field which would contain all the names between the first and the last. Full name can then be computed by concatenating these 3 fields (*preferred*)

-- OR --

* Remove first and last, and only have full name (simpler, but then the data becomes less granular)

**Comment by rgreinho** [comment]
Done in #199.
