### ISSUE TITLE
Multiple fatalities in one crash are not handled properly (and 'Notes' are missing)

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapd#77]
Issue Type
----------

- Bug report

Current Behavior
----------------

When there are multiple fatalities in a crash, the information about the victims are not retrieved.

For instance: https://austintexas.gov/news/traffic-fatality-15-4

Notes that in this example, the `Notes` field is not parse correctly either.

Expected Behavior
-----------------

Not sure exactly what to do here are, as ScrAPD manages the number of crashes, not the number of victims.

However, in spite of that, the `Notes` should be parsed.

**Comment by rgreinho** [comment]
Closed by #90.

**Comment by mscarey** [comment]
I looked at https://austintexas.gov/news/traffic-fatality-15-4 in handling #81, and this issue doesn't seem to be fixed, either before or after my pull request.

**Comment by rgreinho** [comment]
The https://austintexas.gov/news/traffic-fatality-15-4 report looks good actually. Except for the notes. But for our parsing, it works as the first deceased person is parsed correctly (`Garrett Evan Davis | White male | 06/24/1991`). Our data structure does not allow us to store more than one deceased information, therefore the compromise was to be able to parse to first one.


```json
[
  {
    "Age": 27,
    "Case": "19-0921776",
    "DOB": "06/24/1991",
    "Date": "04/02/2019",
    "Ethnicity": "White",
    "Fatal crashes this year": "15",
    "First Name": "Garrett",
    "Gender": "male",
    "Last Name": "Davis",
    "Link": "http://austintexas.gov/news/traffic-fatality-15-4",
    "Location": "517 E. Slaughter Lane",
    "Notes": "This is Austin\u2019s 15th fatal traffic crash of 2019, resulting in 15 fatalities this year. At this time in 2018, there were 15 fatal traffic crashes and 16 traffic fatalities.",
    "Time": "10:01 p.m."
  }
]
```
