### ISSUE TITLE
`Deceased` fields using `XX years of age` throw the parser off.

### ISSUE THREAD

**Issue by rgreinho** [scrapd/scrapd#92]
Issue Type
----------

- Bug report

Current Behavior
----------------

`Deceased` fields using `XX years of age` throw the parser off.

Example:
`Deceased:  Hispanic male, 19 years of age`: http://austintexas.gov/news/traffic-fatality-20-4
In this case, the parser interprets the date as 2019.

Expected Behavior
-----------------

The parser should extract the age (`19`) and leave the `DOB` field empty.

**Comment by mscarey** [comment]
I'm looking at this one.

**Comment by rgreinho** [comment]
Assigned to @mscarey.

**Comment by rgreinho** [comment]
Closed by #125.
