### ISSUE TITLE
APD.py code cleanup

### ISSUE THREAD

**Issue by mrengler** [scrapd/scrapd#98]
Issue Type
----------
- Feature request

While not a breaking issue, it would be good to make a few changes to the apd.py code to make it cleaner and more readable. These include:
- putting regexes in verbose mode and explaining them
- reducing repetition in the Deceased field parsing functions (could pass in delimiter as a parameter, or something)
- more comments or modularity where appropriate to handle "special cases" of parsing

Context
-------
As new contributors join the project, these changes will make it easier for them to understand what's going on and ultimately make us more effective at debugging and adding functionality.

**Comment by rgreinho** [comment]
@mrengler a lot of worked was done around the tasks you mentioned. Once PRs #138, #139, and #140 get merged, I think this ticket will be fully done.

Let me know what you think and if you agree we could close it.
